### ISSUE TITLE
 Blockchain Money problem!

### ISSUE THREAD

**Issue by DwS5KaMxi2pZ3Lw** [TadavomnisT/SeRCH#1]
what is  blockchain financial interest for data savers? You can get some money from users to register their public key. It is better to apply blockchain on the etherium.

**Comment by TadavomnisT** [comment]
@DwS5KaMxi2pZ3Lw 

Hello there!

I suppose people might be wondering where did this whole `blockchain` thing came from all of a sudden!

That's why I created this issue #2 .

I think it might be a good idea to submit your great idea of having blockchain in that issue , then we keep up with this  **Blockchain Money problem!**
